// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/scanner.proto

package scannerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScanStatus int32

const (
	ScanStatus_Scan_STATUS_UNSPECIFIED ScanStatus = 0
	ScanStatus_Scan_STATUS_PENDING     ScanStatus = 1
	ScanStatus_Scan_STATUS_PROCESSING  ScanStatus = 2
	ScanStatus_Scan_STATUS_COMPLETED   ScanStatus = 3
	ScanStatus_Scan_STATUS_FAILED      ScanStatus = 4
	ScanStatus_Scan_STATUS_CANCELLED   ScanStatus = 5
)

// Enum value maps for ScanStatus.
var (
	ScanStatus_name = map[int32]string{
		0: "Scan_STATUS_UNSPECIFIED",
		1: "Scan_STATUS_PENDING",
		2: "Scan_STATUS_PROCESSING",
		3: "Scan_STATUS_COMPLETED",
		4: "Scan_STATUS_FAILED",
		5: "Scan_STATUS_CANCELLED",
	}
	ScanStatus_value = map[string]int32{
		"Scan_STATUS_UNSPECIFIED": 0,
		"Scan_STATUS_PENDING":     1,
		"Scan_STATUS_PROCESSING":  2,
		"Scan_STATUS_COMPLETED":   3,
		"Scan_STATUS_FAILED":      4,
		"Scan_STATUS_CANCELLED":   5,
	}
)

func (x ScanStatus) Enum() *ScanStatus {
	p := new(ScanStatus)
	*p = x
	return p
}

func (x ScanStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScanStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_scanner_proto_enumTypes[0].Descriptor()
}

func (ScanStatus) Type() protoreflect.EnumType {
	return &file_proto_scanner_proto_enumTypes[0]
}

func (x ScanStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScanStatus.Descriptor instead.
func (ScanStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_scanner_proto_rawDescGZIP(), []int{0}
}

type SendFileRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	ScanId string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*SendFileRequest_Info
	//	*SendFileRequest_ChunkData
	//	*SendFileRequest_Done
	Data          isSendFileRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFileRequest) Reset() {
	*x = SendFileRequest{}
	mi := &file_proto_scanner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileRequest) ProtoMessage() {}

func (x *SendFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileRequest.ProtoReflect.Descriptor instead.
func (*SendFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_scanner_proto_rawDescGZIP(), []int{0}
}

func (x *SendFileRequest) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *SendFileRequest) GetData() isSendFileRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SendFileRequest) GetInfo() *FileInfo {
	if x != nil {
		if x, ok := x.Data.(*SendFileRequest_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *SendFileRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Data.(*SendFileRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

func (x *SendFileRequest) GetDone() bool {
	if x != nil {
		if x, ok := x.Data.(*SendFileRequest_Done); ok {
			return x.Done
		}
	}
	return false
}

type isSendFileRequest_Data interface {
	isSendFileRequest_Data()
}

type SendFileRequest_Info struct {
	Info *FileInfo `protobuf:"bytes,2,opt,name=info,proto3,oneof"`
}

type SendFileRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,3,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

type SendFileRequest_Done struct {
	Done bool `protobuf:"varint,4,opt,name=done,proto3,oneof"`
}

func (*SendFileRequest_Info) isSendFileRequest_Data() {}

func (*SendFileRequest_ChunkData) isSendFileRequest_Data() {}

func (*SendFileRequest_Done) isSendFileRequest_Data() {}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_proto_scanner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_proto_scanner_proto_rawDescGZIP(), []int{1}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SendFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFileResponse) Reset() {
	*x = SendFileResponse{}
	mi := &file_proto_scanner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileResponse) ProtoMessage() {}

func (x *SendFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileResponse.ProtoReflect.Descriptor instead.
func (*SendFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_scanner_proto_rawDescGZIP(), []int{2}
}

type Scan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	File          *FileScanResult        `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
	Status        ScanStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=scanner.ScanStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scan) Reset() {
	*x = Scan{}
	mi := &file_proto_scanner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scan) ProtoMessage() {}

func (x *Scan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scan.ProtoReflect.Descriptor instead.
func (*Scan) Descriptor() ([]byte, []int) {
	return file_proto_scanner_proto_rawDescGZIP(), []int{3}
}

func (x *Scan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Scan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Scan) GetFile() *FileScanResult {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *Scan) GetStatus() ScanStatus {
	if x != nil {
		return x.Status
	}
	return ScanStatus_Scan_STATUS_UNSPECIFIED
}

type FileScanResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ScanFinished  bool                   `protobuf:"varint,2,opt,name=scan_finished,json=scanFinished,proto3" json:"scan_finished,omitempty"`
	Result        []*ScannerResult       `protobuf:"bytes,3,rep,name=Result,proto3" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileScanResult) Reset() {
	*x = FileScanResult{}
	mi := &file_proto_scanner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileScanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileScanResult) ProtoMessage() {}

func (x *FileScanResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileScanResult.ProtoReflect.Descriptor instead.
func (*FileScanResult) Descriptor() ([]byte, []int) {
	return file_proto_scanner_proto_rawDescGZIP(), []int{4}
}

func (x *FileScanResult) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileScanResult) GetScanFinished() bool {
	if x != nil {
		return x.ScanFinished
	}
	return false
}

func (x *FileScanResult) GetResult() []*ScannerResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ScannerResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScannerName   string                 `protobuf:"bytes,1,opt,name=scanner_name,json=scannerName,proto3" json:"scanner_name,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScannerResult) Reset() {
	*x = ScannerResult{}
	mi := &file_proto_scanner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScannerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScannerResult) ProtoMessage() {}

func (x *ScannerResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScannerResult.ProtoReflect.Descriptor instead.
func (*ScannerResult) Descriptor() ([]byte, []int) {
	return file_proto_scanner_proto_rawDescGZIP(), []int{5}
}

func (x *ScannerResult) GetScannerName() string {
	if x != nil {
		return x.ScannerName
	}
	return ""
}

func (x *ScannerResult) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type CreateScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // bool start_scan = 2;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScanRequest) Reset() {
	*x = CreateScanRequest{}
	mi := &file_proto_scanner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScanRequest) ProtoMessage() {}

func (x *CreateScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScanRequest.ProtoReflect.Descriptor instead.
func (*CreateScanRequest) Descriptor() ([]byte, []int) {
	return file_proto_scanner_proto_rawDescGZIP(), []int{6}
}

func (x *CreateScanRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ScanId        string                 `protobuf:"bytes,2,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScanResponse) Reset() {
	*x = CreateScanResponse{}
	mi := &file_proto_scanner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScanResponse) ProtoMessage() {}

func (x *CreateScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScanResponse.ProtoReflect.Descriptor instead.
func (*CreateScanResponse) Descriptor() ([]byte, []int) {
	return file_proto_scanner_proto_rawDescGZIP(), []int{7}
}

func (x *CreateScanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateScanResponse) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *CreateScanResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetScanResultByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScanResultByIDRequest) Reset() {
	*x = GetScanResultByIDRequest{}
	mi := &file_proto_scanner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScanResultByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScanResultByIDRequest) ProtoMessage() {}

func (x *GetScanResultByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScanResultByIDRequest.ProtoReflect.Descriptor instead.
func (*GetScanResultByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_scanner_proto_rawDescGZIP(), []int{8}
}

func (x *GetScanResultByIDRequest) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

type GetScanResultByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Scan          *Scan                  `protobuf:"bytes,2,opt,name=Scan,proto3" json:"Scan,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScanResultByIDResponse) Reset() {
	*x = GetScanResultByIDResponse{}
	mi := &file_proto_scanner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScanResultByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScanResultByIDResponse) ProtoMessage() {}

func (x *GetScanResultByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScanResultByIDResponse.ProtoReflect.Descriptor instead.
func (*GetScanResultByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_scanner_proto_rawDescGZIP(), []int{9}
}

func (x *GetScanResultByIDResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetScanResultByIDResponse) GetScan() *Scan {
	if x != nil {
		return x.Scan
	}
	return nil
}

func (x *GetScanResultByIDResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusFilter  ScanStatus             `protobuf:"varint,1,opt,name=status_filter,json=statusFilter,proto3,enum=scanner.ScanStatus" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_proto_scanner_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_scanner_proto_rawDescGZIP(), []int{10}
}

func (x *GetHistoryRequest) GetStatusFilter() ScanStatus {
	if x != nil {
		return x.StatusFilter
	}
	return ScanStatus_Scan_STATUS_UNSPECIFIED
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scans         []*Scan                `protobuf:"bytes,1,rep,name=Scans,proto3" json:"Scans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_proto_scanner_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_scanner_proto_rawDescGZIP(), []int{11}
}

func (x *GetHistoryResponse) GetScans() []*Scan {
	if x != nil {
		return x.Scans
	}
	return nil
}

var File_proto_scanner_proto protoreflect.FileDescriptor

const file_proto_scanner_proto_rawDesc = "" +
	"\n" +
	"\x13proto/scanner.proto\x12\ascanner\"\x92\x01\n" +
	"\x0fSendFileRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12'\n" +
	"\x04info\x18\x02 \x01(\v2\x11.scanner.FileInfoH\x00R\x04info\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x03 \x01(\fH\x00R\tchunkData\x12\x14\n" +
	"\x04done\x18\x04 \x01(\bH\x00R\x04doneB\x06\n" +
	"\x04data\"2\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\"\x12\n" +
	"\x10SendFileResponse\"\x84\x01\n" +
	"\x04Scan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12+\n" +
	"\x04file\x18\x04 \x01(\v2\x17.scanner.FileScanResultR\x04file\x12+\n" +
	"\x06status\x18\x05 \x01(\x0e2\x13.scanner.ScanStatusR\x06status\"\x82\x01\n" +
	"\x0eFileScanResult\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12#\n" +
	"\rscan_finished\x18\x02 \x01(\bR\fscanFinished\x12.\n" +
	"\x06Result\x18\x03 \x03(\v2\x16.scanner.ScannerResultR\x06Result\"J\n" +
	"\rScannerResult\x12!\n" +
	"\fscanner_name\x18\x01 \x01(\tR\vscannerName\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\"'\n" +
	"\x11CreateScanRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"a\n" +
	"\x12CreateScanResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\ascan_id\x18\x02 \x01(\tR\x06scanId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"3\n" +
	"\x18GetScanResultByIDRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\"j\n" +
	"\x19GetScanResultByIDResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12!\n" +
	"\x04Scan\x18\x02 \x01(\v2\r.scanner.ScanR\x04Scan\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"M\n" +
	"\x11GetHistoryRequest\x128\n" +
	"\rstatus_filter\x18\x01 \x01(\x0e2\x13.scanner.ScanStatusR\fstatusFilter\"9\n" +
	"\x12GetHistoryResponse\x12#\n" +
	"\x05Scans\x18\x01 \x03(\v2\r.scanner.ScanR\x05Scans*\xac\x01\n" +
	"\n" +
	"ScanStatus\x12\x1b\n" +
	"\x17Scan_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13Scan_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16Scan_STATUS_PROCESSING\x10\x02\x12\x19\n" +
	"\x15Scan_STATUS_COMPLETED\x10\x03\x12\x16\n" +
	"\x12Scan_STATUS_FAILED\x10\x04\x12\x19\n" +
	"\x15Scan_STATUS_CANCELLED\x10\x052\xbd\x02\n" +
	"\x0eScannerService\x12E\n" +
	"\n" +
	"CreateScan\x12\x1a.scanner.CreateScanRequest\x1a\x1b.scanner.CreateScanResponse\x12A\n" +
	"\bSendFile\x12\x18.scanner.SendFileRequest\x1a\x19.scanner.SendFileResponse(\x01\x12Z\n" +
	"\x11GetScanResultByID\x12!.scanner.GetScanResultByIDRequest\x1a\".scanner.GetScanResultByIDResponse\x12E\n" +
	"\n" +
	"GetHistory\x12\x1a.scanner.GetHistoryRequest\x1a\x1b.scanner.GetHistoryResponseB\x17Z\x15./scannerpb;scannerpbb\x06proto3"

var (
	file_proto_scanner_proto_rawDescOnce sync.Once
	file_proto_scanner_proto_rawDescData []byte
)

func file_proto_scanner_proto_rawDescGZIP() []byte {
	file_proto_scanner_proto_rawDescOnce.Do(func() {
		file_proto_scanner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scanner_proto_rawDesc), len(file_proto_scanner_proto_rawDesc)))
	})
	return file_proto_scanner_proto_rawDescData
}

var file_proto_scanner_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_scanner_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_scanner_proto_goTypes = []any{
	(ScanStatus)(0),                   // 0: scanner.ScanStatus
	(*SendFileRequest)(nil),           // 1: scanner.SendFileRequest
	(*FileInfo)(nil),                  // 2: scanner.FileInfo
	(*SendFileResponse)(nil),          // 3: scanner.SendFileResponse
	(*Scan)(nil),                      // 4: scanner.Scan
	(*FileScanResult)(nil),            // 5: scanner.FileScanResult
	(*ScannerResult)(nil),             // 6: scanner.ScannerResult
	(*CreateScanRequest)(nil),         // 7: scanner.CreateScanRequest
	(*CreateScanResponse)(nil),        // 8: scanner.CreateScanResponse
	(*GetScanResultByIDRequest)(nil),  // 9: scanner.GetScanResultByIDRequest
	(*GetScanResultByIDResponse)(nil), // 10: scanner.GetScanResultByIDResponse
	(*GetHistoryRequest)(nil),         // 11: scanner.GetHistoryRequest
	(*GetHistoryResponse)(nil),        // 12: scanner.GetHistoryResponse
}
var file_proto_scanner_proto_depIdxs = []int32{
	2,  // 0: scanner.SendFileRequest.info:type_name -> scanner.FileInfo
	5,  // 1: scanner.Scan.file:type_name -> scanner.FileScanResult
	0,  // 2: scanner.Scan.status:type_name -> scanner.ScanStatus
	6,  // 3: scanner.FileScanResult.Result:type_name -> scanner.ScannerResult
	4,  // 4: scanner.GetScanResultByIDResponse.Scan:type_name -> scanner.Scan
	0,  // 5: scanner.GetHistoryRequest.status_filter:type_name -> scanner.ScanStatus
	4,  // 6: scanner.GetHistoryResponse.Scans:type_name -> scanner.Scan
	7,  // 7: scanner.ScannerService.CreateScan:input_type -> scanner.CreateScanRequest
	1,  // 8: scanner.ScannerService.SendFile:input_type -> scanner.SendFileRequest
	9,  // 9: scanner.ScannerService.GetScanResultByID:input_type -> scanner.GetScanResultByIDRequest
	11, // 10: scanner.ScannerService.GetHistory:input_type -> scanner.GetHistoryRequest
	8,  // 11: scanner.ScannerService.CreateScan:output_type -> scanner.CreateScanResponse
	3,  // 12: scanner.ScannerService.SendFile:output_type -> scanner.SendFileResponse
	10, // 13: scanner.ScannerService.GetScanResultByID:output_type -> scanner.GetScanResultByIDResponse
	12, // 14: scanner.ScannerService.GetHistory:output_type -> scanner.GetHistoryResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_scanner_proto_init() }
func file_proto_scanner_proto_init() {
	if File_proto_scanner_proto != nil {
		return
	}
	file_proto_scanner_proto_msgTypes[0].OneofWrappers = []any{
		(*SendFileRequest_Info)(nil),
		(*SendFileRequest_ChunkData)(nil),
		(*SendFileRequest_Done)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scanner_proto_rawDesc), len(file_proto_scanner_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scanner_proto_goTypes,
		DependencyIndexes: file_proto_scanner_proto_depIdxs,
		EnumInfos:         file_proto_scanner_proto_enumTypes,
		MessageInfos:      file_proto_scanner_proto_msgTypes,
	}.Build()
	File_proto_scanner_proto = out.File
	file_proto_scanner_proto_goTypes = nil
	file_proto_scanner_proto_depIdxs = nil
}
