version: "3.9"

services:

  api-service:
    image: mrtdeh/api
    container_name: api-service
    environment:
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=8080
      - SCANNER_ADDR=scanner-service:10000
    ports:
      - "8080:8080" 


  scanner-service:
    image: mrtdeh/scanner
    container_name: scanner-service
    environment:
      - GRPC_HOST=0.0.0.0

      - MONGO_HOST=mongodb
      - MONGO_USER=admin
      - MONGO_PASS=admin

      # - YARA_RULES_PATH=/home/yara-rules
      - YARA_CONTAINER_NAME=yara-service
      - YARA_SCAN_ROOT=/data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - shared_data:/data

  yara-service:
    image: mrtdeh/yara-service
    container_name: yara-service
    volumes:
      - /home/yara-rules:/rules
      - shared_data:/data




  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db


volumes:
  mongodb_data:
  shared_data:

