// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: create_scan.proto

package scannerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Files         []*FileRequest         `protobuf:"bytes,2,rep,name=Files,proto3" json:"Files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScanRequest) Reset() {
	*x = CreateScanRequest{}
	mi := &file_create_scan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScanRequest) ProtoMessage() {}

func (x *CreateScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_create_scan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScanRequest.ProtoReflect.Descriptor instead.
func (*CreateScanRequest) Descriptor() ([]byte, []int) {
	return file_create_scan_proto_rawDescGZIP(), []int{0}
}

func (x *CreateScanRequest) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *CreateScanRequest) GetFiles() []*FileRequest {
	if x != nil {
		return x.Files
	}
	return nil
}

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_create_scan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_create_scan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_create_scan_proto_rawDescGZIP(), []int{1}
}

func (x *FileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *FileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type CreateScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ScanId        string                 `protobuf:"bytes,2,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	States        []*FileScanResultState `protobuf:"bytes,4,rep,name=states,proto3" json:"states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScanResponse) Reset() {
	*x = CreateScanResponse{}
	mi := &file_create_scan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScanResponse) ProtoMessage() {}

func (x *CreateScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_create_scan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScanResponse.ProtoReflect.Descriptor instead.
func (*CreateScanResponse) Descriptor() ([]byte, []int) {
	return file_create_scan_proto_rawDescGZIP(), []int{2}
}

func (x *CreateScanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateScanResponse) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *CreateScanResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateScanResponse) GetStates() []*FileScanResultState {
	if x != nil {
		return x.States
	}
	return nil
}

type FileScanResultState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Cached        bool                   `protobuf:"varint,2,opt,name=cached,proto3" json:"cached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileScanResultState) Reset() {
	*x = FileScanResultState{}
	mi := &file_create_scan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileScanResultState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileScanResultState) ProtoMessage() {}

func (x *FileScanResultState) ProtoReflect() protoreflect.Message {
	mi := &file_create_scan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileScanResultState.ProtoReflect.Descriptor instead.
func (*FileScanResultState) Descriptor() ([]byte, []int) {
	return file_create_scan_proto_rawDescGZIP(), []int{3}
}

func (x *FileScanResultState) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileScanResultState) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

var File_create_scan_proto protoreflect.FileDescriptor

const file_create_scan_proto_rawDesc = "" +
	"\n" +
	"\x11create_scan.proto\x12\ascanner\"X\n" +
	"\x11CreateScanRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12*\n" +
	"\x05Files\x18\x02 \x03(\v2\x14.scanner.FileRequestR\x05Files\"b\n" +
	"\vFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"\x97\x01\n" +
	"\x12CreateScanResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\ascan_id\x18\x02 \x01(\tR\x06scanId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x124\n" +
	"\x06states\x18\x04 \x03(\v2\x1c.scanner.FileScanResultStateR\x06states\"F\n" +
	"\x13FileScanResultState\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x16\n" +
	"\x06cached\x18\x02 \x01(\bR\x06cachedB\x10Z\x0e./pb;scannerpbb\x06proto3"

var (
	file_create_scan_proto_rawDescOnce sync.Once
	file_create_scan_proto_rawDescData []byte
)

func file_create_scan_proto_rawDescGZIP() []byte {
	file_create_scan_proto_rawDescOnce.Do(func() {
		file_create_scan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_create_scan_proto_rawDesc), len(file_create_scan_proto_rawDesc)))
	})
	return file_create_scan_proto_rawDescData
}

var file_create_scan_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_create_scan_proto_goTypes = []any{
	(*CreateScanRequest)(nil),   // 0: scanner.CreateScanRequest
	(*FileRequest)(nil),         // 1: scanner.FileRequest
	(*CreateScanResponse)(nil),  // 2: scanner.CreateScanResponse
	(*FileScanResultState)(nil), // 3: scanner.FileScanResultState
}
var file_create_scan_proto_depIdxs = []int32{
	1, // 0: scanner.CreateScanRequest.Files:type_name -> scanner.FileRequest
	3, // 1: scanner.CreateScanResponse.states:type_name -> scanner.FileScanResultState
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_create_scan_proto_init() }
func file_create_scan_proto_init() {
	if File_create_scan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_create_scan_proto_rawDesc), len(file_create_scan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_create_scan_proto_goTypes,
		DependencyIndexes: file_create_scan_proto_depIdxs,
		MessageInfos:      file_create_scan_proto_msgTypes,
	}.Build()
	File_create_scan_proto = out.File
	file_create_scan_proto_goTypes = nil
	file_create_scan_proto_depIdxs = nil
}
