// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: get_history.proto

package scannerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScanStatus int32

const (
	ScanStatus_Scan_STATUS_UNSPECIFIED ScanStatus = 0
	ScanStatus_Scan_STATUS_PENDING     ScanStatus = 1
	ScanStatus_Scan_STATUS_PROCESSING  ScanStatus = 2
	ScanStatus_Scan_STATUS_COMPLETED   ScanStatus = 3
	ScanStatus_Scan_STATUS_FAILED      ScanStatus = 4
	ScanStatus_Scan_STATUS_CANCELLED   ScanStatus = 5
)

// Enum value maps for ScanStatus.
var (
	ScanStatus_name = map[int32]string{
		0: "Scan_STATUS_UNSPECIFIED",
		1: "Scan_STATUS_PENDING",
		2: "Scan_STATUS_PROCESSING",
		3: "Scan_STATUS_COMPLETED",
		4: "Scan_STATUS_FAILED",
		5: "Scan_STATUS_CANCELLED",
	}
	ScanStatus_value = map[string]int32{
		"Scan_STATUS_UNSPECIFIED": 0,
		"Scan_STATUS_PENDING":     1,
		"Scan_STATUS_PROCESSING":  2,
		"Scan_STATUS_COMPLETED":   3,
		"Scan_STATUS_FAILED":      4,
		"Scan_STATUS_CANCELLED":   5,
	}
)

func (x ScanStatus) Enum() *ScanStatus {
	p := new(ScanStatus)
	*p = x
	return p
}

func (x ScanStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScanStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_get_history_proto_enumTypes[0].Descriptor()
}

func (ScanStatus) Type() protoreflect.EnumType {
	return &file_get_history_proto_enumTypes[0]
}

func (x ScanStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScanStatus.Descriptor instead.
func (ScanStatus) EnumDescriptor() ([]byte, []int) {
	return file_get_history_proto_rawDescGZIP(), []int{0}
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusFilter  ScanStatus             `protobuf:"varint,1,opt,name=status_filter,json=statusFilter,proto3,enum=scanner.ScanStatus" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_get_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_get_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_get_history_proto_rawDescGZIP(), []int{0}
}

func (x *GetHistoryRequest) GetStatusFilter() ScanStatus {
	if x != nil {
		return x.StatusFilter
	}
	return ScanStatus_Scan_STATUS_UNSPECIFIED
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scans         []*ScanResponse        `protobuf:"bytes,1,rep,name=Scans,proto3" json:"Scans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_get_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_get_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_get_history_proto_rawDescGZIP(), []int{1}
}

func (x *GetHistoryResponse) GetScans() []*ScanResponse {
	if x != nil {
		return x.Scans
	}
	return nil
}

var File_get_history_proto protoreflect.FileDescriptor

const file_get_history_proto_rawDesc = "" +
	"\n" +
	"\x11get_history.proto\x12\ascanner\x1a\x13scan_response.proto\"M\n" +
	"\x11GetHistoryRequest\x128\n" +
	"\rstatus_filter\x18\x01 \x01(\x0e2\x13.scanner.ScanStatusR\fstatusFilter\"A\n" +
	"\x12GetHistoryResponse\x12+\n" +
	"\x05Scans\x18\x01 \x03(\v2\x15.scanner.ScanResponseR\x05Scans*\xac\x01\n" +
	"\n" +
	"ScanStatus\x12\x1b\n" +
	"\x17Scan_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13Scan_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16Scan_STATUS_PROCESSING\x10\x02\x12\x19\n" +
	"\x15Scan_STATUS_COMPLETED\x10\x03\x12\x16\n" +
	"\x12Scan_STATUS_FAILED\x10\x04\x12\x19\n" +
	"\x15Scan_STATUS_CANCELLED\x10\x05B\x10Z\x0e./pb;scannerpbb\x06proto3"

var (
	file_get_history_proto_rawDescOnce sync.Once
	file_get_history_proto_rawDescData []byte
)

func file_get_history_proto_rawDescGZIP() []byte {
	file_get_history_proto_rawDescOnce.Do(func() {
		file_get_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_get_history_proto_rawDesc), len(file_get_history_proto_rawDesc)))
	})
	return file_get_history_proto_rawDescData
}

var file_get_history_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_get_history_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_get_history_proto_goTypes = []any{
	(ScanStatus)(0),            // 0: scanner.ScanStatus
	(*GetHistoryRequest)(nil),  // 1: scanner.GetHistoryRequest
	(*GetHistoryResponse)(nil), // 2: scanner.GetHistoryResponse
	(*ScanResponse)(nil),       // 3: scanner.ScanResponse
}
var file_get_history_proto_depIdxs = []int32{
	0, // 0: scanner.GetHistoryRequest.status_filter:type_name -> scanner.ScanStatus
	3, // 1: scanner.GetHistoryResponse.Scans:type_name -> scanner.ScanResponse
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_get_history_proto_init() }
func file_get_history_proto_init() {
	if File_get_history_proto != nil {
		return
	}
	file_scan_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_get_history_proto_rawDesc), len(file_get_history_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_get_history_proto_goTypes,
		DependencyIndexes: file_get_history_proto_depIdxs,
		EnumInfos:         file_get_history_proto_enumTypes,
		MessageInfos:      file_get_history_proto_msgTypes,
	}.Build()
	File_get_history_proto = out.File
	file_get_history_proto_goTypes = nil
	file_get_history_proto_depIdxs = nil
}
