// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: main.proto

package scannerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_main_proto protoreflect.FileDescriptor

const file_main_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"main.proto\x12\ascanner\x1a\x11create_scan.proto\x1a\x0fsend_file.proto\x1a\x1bget_scan_result_by_id.proto\x1a\x11get_history.proto2\xbd\x02\n" +
	"\x0eScannerService\x12E\n" +
	"\n" +
	"CreateScan\x12\x1a.scanner.CreateScanRequest\x1a\x1b.scanner.CreateScanResponse\x12A\n" +
	"\bSendFile\x12\x18.scanner.SendFileRequest\x1a\x19.scanner.SendFileResponse(\x01\x12Z\n" +
	"\x11GetScanResultByID\x12!.scanner.GetScanResultByIDRequest\x1a\".scanner.GetScanResultByIDResponse\x12E\n" +
	"\n" +
	"GetHistory\x12\x1a.scanner.GetHistoryRequest\x1a\x1b.scanner.GetHistoryResponseB\x10Z\x0e./pb;scannerpbb\x06proto3"

var file_main_proto_goTypes = []any{
	(*CreateScanRequest)(nil),         // 0: scanner.CreateScanRequest
	(*SendFileRequest)(nil),           // 1: scanner.SendFileRequest
	(*GetScanResultByIDRequest)(nil),  // 2: scanner.GetScanResultByIDRequest
	(*GetHistoryRequest)(nil),         // 3: scanner.GetHistoryRequest
	(*CreateScanResponse)(nil),        // 4: scanner.CreateScanResponse
	(*SendFileResponse)(nil),          // 5: scanner.SendFileResponse
	(*GetScanResultByIDResponse)(nil), // 6: scanner.GetScanResultByIDResponse
	(*GetHistoryResponse)(nil),        // 7: scanner.GetHistoryResponse
}
var file_main_proto_depIdxs = []int32{
	0, // 0: scanner.ScannerService.CreateScan:input_type -> scanner.CreateScanRequest
	1, // 1: scanner.ScannerService.SendFile:input_type -> scanner.SendFileRequest
	2, // 2: scanner.ScannerService.GetScanResultByID:input_type -> scanner.GetScanResultByIDRequest
	3, // 3: scanner.ScannerService.GetHistory:input_type -> scanner.GetHistoryRequest
	4, // 4: scanner.ScannerService.CreateScan:output_type -> scanner.CreateScanResponse
	5, // 5: scanner.ScannerService.SendFile:output_type -> scanner.SendFileResponse
	6, // 6: scanner.ScannerService.GetScanResultByID:output_type -> scanner.GetScanResultByIDResponse
	7, // 7: scanner.ScannerService.GetHistory:output_type -> scanner.GetHistoryResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_main_proto_init() }
func file_main_proto_init() {
	if File_main_proto != nil {
		return
	}
	file_create_scan_proto_init()
	file_send_file_proto_init()
	file_get_scan_result_by_id_proto_init()
	file_get_history_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_main_proto_rawDesc), len(file_main_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_main_proto_goTypes,
		DependencyIndexes: file_main_proto_depIdxs,
	}.Build()
	File_main_proto = out.File
	file_main_proto_goTypes = nil
	file_main_proto_depIdxs = nil
}
