// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: scan_response.proto

package scannerpb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Time struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Time) Reset() {
	*x = Time{}
	mi := &file_scan_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Time) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Time) ProtoMessage() {}

func (x *Time) ProtoReflect() protoreflect.Message {
	mi := &file_scan_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Time.ProtoReflect.Descriptor instead.
func (*Time) Descriptor() ([]byte, []int) {
	return file_scan_response_proto_rawDescGZIP(), []int{0}
}

func (x *Time) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Results       []*ScanResult          `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	StartedAt     *Time                  `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *Time                  `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_scan_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scan_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_scan_response_proto_rawDescGZIP(), []int{1}
}

func (x *ScanResponse) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *ScanResponse) GetResults() []*ScanResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ScanResponse) GetStartedAt() *Time {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ScanResponse) GetCompletedAt() *Time {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type ScanResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Result        []*ScannerResult       `protobuf:"bytes,2,rep,name=Result,proto3" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResult) Reset() {
	*x = ScanResult{}
	mi := &file_scan_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResult) ProtoMessage() {}

func (x *ScanResult) ProtoReflect() protoreflect.Message {
	mi := &file_scan_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResult.ProtoReflect.Descriptor instead.
func (*ScanResult) Descriptor() ([]byte, []int) {
	return file_scan_response_proto_rawDescGZIP(), []int{2}
}

func (x *ScanResult) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ScanResult) GetResult() []*ScannerResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ScannerResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Engine        string                 `protobuf:"bytes,1,opt,name=engine,proto3" json:"engine,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     *Time                  `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *Time                  `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScannerResult) Reset() {
	*x = ScannerResult{}
	mi := &file_scan_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScannerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScannerResult) ProtoMessage() {}

func (x *ScannerResult) ProtoReflect() protoreflect.Message {
	mi := &file_scan_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScannerResult.ProtoReflect.Descriptor instead.
func (*ScannerResult) Descriptor() ([]byte, []int) {
	return file_scan_response_proto_rawDescGZIP(), []int{3}
}

func (x *ScannerResult) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *ScannerResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ScannerResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScannerResult) GetStartedAt() *Time {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ScannerResult) GetCompletedAt() *Time {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *ScannerResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_scan_response_proto protoreflect.FileDescriptor

const file_scan_response_proto_rawDesc = "" +
	"\n" +
	"\x13scan_response.proto\x12\ascanner\x1a\x1fgoogle/protobuf/timestamp.proto\"@\n" +
	"\x04time\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xb6\x01\n" +
	"\fScanResponse\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12-\n" +
	"\aresults\x18\x03 \x03(\v2\x13.scanner.ScanResultR\aresults\x12,\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\r.scanner.timeR\tstartedAt\x120\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\r.scanner.timeR\vcompletedAt\"Y\n" +
	"\n" +
	"ScanResult\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12.\n" +
	"\x06Result\x18\x02 \x03(\v2\x16.scanner.ScannerResultR\x06Result\"\xcd\x01\n" +
	"\rScannerResult\x12\x16\n" +
	"\x06engine\x18\x01 \x01(\tR\x06engine\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12,\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\r.scanner.timeR\tstartedAt\x120\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\r.scanner.timeR\vcompletedAt\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05errorB\x10Z\x0e./pb;scannerpbb\x06proto3"

var (
	file_scan_response_proto_rawDescOnce sync.Once
	file_scan_response_proto_rawDescData []byte
)

func file_scan_response_proto_rawDescGZIP() []byte {
	file_scan_response_proto_rawDescOnce.Do(func() {
		file_scan_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scan_response_proto_rawDesc), len(file_scan_response_proto_rawDesc)))
	})
	return file_scan_response_proto_rawDescData
}

var file_scan_response_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_scan_response_proto_goTypes = []any{
	(*Time)(nil),                // 0: scanner.time
	(*ScanResponse)(nil),        // 1: scanner.ScanResponse
	(*ScanResult)(nil),          // 2: scanner.ScanResult
	(*ScannerResult)(nil),       // 3: scanner.ScannerResult
	(*timestamp.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_scan_response_proto_depIdxs = []int32{
	4, // 0: scanner.time.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: scanner.ScanResponse.results:type_name -> scanner.ScanResult
	0, // 2: scanner.ScanResponse.started_at:type_name -> scanner.time
	0, // 3: scanner.ScanResponse.completed_at:type_name -> scanner.time
	3, // 4: scanner.ScanResult.Result:type_name -> scanner.ScannerResult
	0, // 5: scanner.ScannerResult.started_at:type_name -> scanner.time
	0, // 6: scanner.ScannerResult.completed_at:type_name -> scanner.time
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_scan_response_proto_init() }
func file_scan_response_proto_init() {
	if File_scan_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scan_response_proto_rawDesc), len(file_scan_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scan_response_proto_goTypes,
		DependencyIndexes: file_scan_response_proto_depIdxs,
		MessageInfos:      file_scan_response_proto_msgTypes,
	}.Build()
	File_scan_response_proto = out.File
	file_scan_response_proto_goTypes = nil
	file_scan_response_proto_depIdxs = nil
}
