// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: send_file.proto

package scannerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*SendFileRequest_Info
	//	*SendFileRequest_ChunkData
	Data          isSendFileRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFileRequest) Reset() {
	*x = SendFileRequest{}
	mi := &file_send_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileRequest) ProtoMessage() {}

func (x *SendFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_send_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileRequest.ProtoReflect.Descriptor instead.
func (*SendFileRequest) Descriptor() ([]byte, []int) {
	return file_send_file_proto_rawDescGZIP(), []int{0}
}

func (x *SendFileRequest) GetData() isSendFileRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SendFileRequest) GetInfo() *FileHeader {
	if x != nil {
		if x, ok := x.Data.(*SendFileRequest_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *SendFileRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Data.(*SendFileRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isSendFileRequest_Data interface {
	isSendFileRequest_Data()
}

type SendFileRequest_Info struct {
	Info *FileHeader `protobuf:"bytes,3,opt,name=info,proto3,oneof"`
}

type SendFileRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,4,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*SendFileRequest_Info) isSendFileRequest_Data() {}

func (*SendFileRequest_ChunkData) isSendFileRequest_Data() {}

type FileHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileHeader) Reset() {
	*x = FileHeader{}
	mi := &file_send_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileHeader) ProtoMessage() {}

func (x *FileHeader) ProtoReflect() protoreflect.Message {
	mi := &file_send_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileHeader.ProtoReflect.Descriptor instead.
func (*FileHeader) Descriptor() ([]byte, []int) {
	return file_send_file_proto_rawDescGZIP(), []int{1}
}

func (x *FileHeader) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *FileHeader) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type SendFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFileResponse) Reset() {
	*x = SendFileResponse{}
	mi := &file_send_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileResponse) ProtoMessage() {}

func (x *SendFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_send_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileResponse.ProtoReflect.Descriptor instead.
func (*SendFileResponse) Descriptor() ([]byte, []int) {
	return file_send_file_proto_rawDescGZIP(), []int{2}
}

var File_send_file_proto protoreflect.FileDescriptor

const file_send_file_proto_rawDesc = "" +
	"\n" +
	"\x0fsend_file.proto\x12\ascanner\"e\n" +
	"\x0fSendFileRequest\x12)\n" +
	"\x04info\x18\x03 \x01(\v2\x13.scanner.FileHeaderH\x00R\x04info\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x04 \x01(\fH\x00R\tchunkDataB\x06\n" +
	"\x04data\">\n" +
	"\n" +
	"FileHeader\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\"\x12\n" +
	"\x10SendFileResponseB\x10Z\x0e./pb;scannerpbb\x06proto3"

var (
	file_send_file_proto_rawDescOnce sync.Once
	file_send_file_proto_rawDescData []byte
)

func file_send_file_proto_rawDescGZIP() []byte {
	file_send_file_proto_rawDescOnce.Do(func() {
		file_send_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_send_file_proto_rawDesc), len(file_send_file_proto_rawDesc)))
	})
	return file_send_file_proto_rawDescData
}

var file_send_file_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_send_file_proto_goTypes = []any{
	(*SendFileRequest)(nil),  // 0: scanner.SendFileRequest
	(*FileHeader)(nil),       // 1: scanner.FileHeader
	(*SendFileResponse)(nil), // 2: scanner.SendFileResponse
}
var file_send_file_proto_depIdxs = []int32{
	1, // 0: scanner.SendFileRequest.info:type_name -> scanner.FileHeader
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_send_file_proto_init() }
func file_send_file_proto_init() {
	if File_send_file_proto != nil {
		return
	}
	file_send_file_proto_msgTypes[0].OneofWrappers = []any{
		(*SendFileRequest_Info)(nil),
		(*SendFileRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_send_file_proto_rawDesc), len(file_send_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_send_file_proto_goTypes,
		DependencyIndexes: file_send_file_proto_depIdxs,
		MessageInfos:      file_send_file_proto_msgTypes,
	}.Build()
	File_send_file_proto = out.File
	file_send_file_proto_goTypes = nil
	file_send_file_proto_depIdxs = nil
}
