syntax = "proto3";
package scanner;
option go_package = "./pb;scannerpb";




import "google/protobuf/timestamp.proto";

message time{
    google.protobuf.Timestamp timestamp = 1;
}

message ScanResponse {
    string scan_id = 1;
    repeated ScanResult results = 3;
    time started_at = 4;
    time completed_at = 5;
}

message ScanResult{
    string file_name = 1;
    repeated ScannerResult Result = 2;
}
message ScannerResult {
    string engine = 1;
    string output = 2;
    string status = 3;
    time started_at = 4;
    time completed_at = 5;
    string error = 6;
}
